#!/usr/bin/env python3
"""Install the read-only TOLF admin inventory on London; grant roles only as root."""
import argparse
import ast
import base64
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import shutil
import sqlite3
import subprocess
import tempfile
import time
import urllib.request
import fcntl

PAYLOAD = 'IiIiQWRtaW4gaW52ZW50b3J5LiBWUE4gbm9kZSBzdGF0ZSBpcyBuZXZlciBpbmZlcnJlZCBmcm9tIHRoZSBhY2NvdW50IGRhdGFiYXNlLiIiIgppbXBvcnQganNvbgppbXBvcnQgc3FsaXRlMwppbXBvcnQgdXVpZAppbXBvcnQgc3VicHJvY2VzcwppbXBvcnQgdGhyZWFkaW5nCmZyb20gY29uY3VycmVudC5mdXR1cmVzIGltcG9ydCBUaHJlYWRQb29sRXhlY3V0b3IKZnJvbSBjb250ZXh0bGliIGltcG9ydCBjb250ZXh0bWFuYWdlcgpmcm9tIGRhdGV0aW1lIGltcG9ydCBkYXRldGltZSwgdGltZXpvbmUKClZFUlNJT04gPSAnMS4xLjAnClNFU1NJT05fUE9MTCA9IHRocmVhZGluZy5Cb3VuZGVkU2VtYXBob3JlKDEpCkhFQURFUlMgPSB7J0NhY2hlLUNvbnRyb2wnOiAncHJpdmF0ZSwgbm8tc3RvcmUsIG1heC1hZ2U9MCcsICdYLUNvbnRlbnQtVHlwZS1PcHRpb25zJzogJ25vc25pZmYnfQpDVFggPSB7fQoKQGNvbnRleHRtYW5hZ2VyCmRlZiBkYigpOgogICAgY29uID0gc3FsaXRlMy5jb25uZWN0KENUWFsnREInXSwgdGltZW91dD0xNSkKICAgIGNvbi5yb3dfZmFjdG9yeSA9IHNxbGl0ZTMuUm93CiAgICB0cnk6CiAgICAgICAgd2l0aCBjb246CiAgICAgICAgICAgIHlpZWxkIGNvbgogICAgZmluYWxseToKICAgICAgICBjb24uY2xvc2UoKQoKCmRlZiBpbml0aWFsaXplKHBhdGgpOgogICAgd2l0aCBzcWxpdGUzLmNvbm5lY3QocGF0aCwgdGltZW91dD0xNSkgYXMgY29uOgogICAgICAgIGNvbi5leGVjdXRlKCdDUkVBVEUgVEFCTEUgSUYgTk9UIEVYSVNUUyBhZG1pbl9yb2xlcyAodXNlcl9pZCBURVhUIFBSSU1BUlkgS0VZLCBncmFudGVkX2F0IFRFWFQgTk9UIE5VTEwsIGdyYW50ZWRfYnkgVEVYVCBOT1QgTlVMTCknKQogICAgICAgIGNvbi5leGVjdXRlKCdDUkVBVEUgVEFCTEUgSUYgTk9UIEVYSVNUUyBhZG1pbl9hdWRpdCAoaWQgSU5URUdFUiBQUklNQVJZIEtFWSBBVVRPSU5DUkVNRU5ULCBhY3RvciBURVhUIE5PVCBOVUxMLCBhY3Rpb24gVEVYVCBOT1QgTlVMTCwgdGFyZ2V0IFRFWFQgTk9UIE5VTEwsIGNyZWF0ZWRfYXQgVEVYVCBOT1QgTlVMTCknKQoKCmRlZiByb290X2dyYW50KHBhdGgsIG51bWJlcik6CiAgICAjIENhbGxlZCBvbmx5IGJ5IHRoZSByb290LW9ubHkgaW5zdGFsbGF0aW9uIHV0aWxpdHksIG5ldmVyIGJ5IGFuIEhUVFAgcm91dGUuCiAgICBpbml0aWFsaXplKHBhdGgpCiAgICB3aXRoIHNxbGl0ZTMuY29ubmVjdChwYXRoLCB0aW1lb3V0PTE1KSBhcyBjb246CiAgICAgICAgY29uLmV4ZWN1dGUoJ0JFR0lOIElNTUVESUFURScpCiAgICAgICAgcm93cyA9IGNvbi5leGVjdXRlKCdTRUxFQ1QgRElTVElOQ1QgdS5pZCBGUk9NIG1hbmFnZWRfdXNlcnMgbSBKT0lOIHVzZXJzIHUgT04gdS5pZD1tLmFjY291bnRfaWQgV0hFUkUgbS5udW1iZXI9PyBBTkQgbS5kZWxldGVkX2F0IElTIE5VTEwnLCAobnVtYmVyLCkpLmZldGNoYWxsKCkKICAgICAgICBpZiBsZW4ocm93cykgIT0gMToKICAgICAgICAgICAgcmFpc2UgVmFsdWVFcnJvcignTnVtYmVyIG11c3QgaWRlbnRpZnkgZXhhY3RseSBvbmUgZXhpc3RpbmcgYWNjb3VudCcpCiAgICAgICAgdXNlcl9pZCA9IHJvd3NbMF1bMF0KICAgICAgICBzdGFtcCA9IGRhdGV0aW1lLm5vdyh0aW1lem9uZS51dGMpLmlzb2Zvcm1hdCgpCiAgICAgICAgaWYgbm90IGNvbi5leGVjdXRlKCdTRUxFQ1QgMSBGUk9NIGFkbWluX3JvbGVzIFdIRVJFIHVzZXJfaWQ9PycsICh1c2VyX2lkLCkpLmZldGNob25lKCk6CiAgICAgICAgICAgIGNvbi5leGVjdXRlKCdJTlNFUlQgSU5UTyBhZG1pbl9yb2xlcyBWQUxVRVMgKD8sPyw/KScsICh1c2VyX2lkLHN0YW1wLCdyb290JykpCiAgICAgICAgICAgIGNvbi5leGVjdXRlKCdJTlNFUlQgSU5UTyBhZG1pbl9hdWRpdChhY3RvcixhY3Rpb24sdGFyZ2V0LGNyZWF0ZWRfYXQpIFZBTFVFUyAoPyw/LD8sPyknLCAoJ3Jvb3QnLCdhZG1pbi5ncmFudCcsdXNlcl9pZCxzdGFtcCkpCiAgICAgICAgcmV0dXJuIHVzZXJfaWQKCgpkZWYgcm9vdF9yZXZva2UocGF0aCwgbnVtYmVyKToKICAgIGluaXRpYWxpemUocGF0aCkKICAgIHdpdGggc3FsaXRlMy5jb25uZWN0KHBhdGgsIHRpbWVvdXQ9MTUpIGFzIGNvbjoKICAgICAgICBjb24uZXhlY3V0ZSgnQkVHSU4gSU1NRURJQVRFJykKICAgICAgICByb3dzID0gY29uLmV4ZWN1dGUoJ1NFTEVDVCBESVNUSU5DVCBhY2NvdW50X2lkIEZST00gbWFuYWdlZF91c2VycyBXSEVSRSBudW1iZXI9PycsIChudW1iZXIsKSkuZmV0Y2hhbGwoKQogICAgICAgIGlmIGxlbihyb3dzKSAhPSAxIG9yIG5vdCByb3dzWzBdWzBdOgogICAgICAgICAgICByYWlzZSBWYWx1ZUVycm9yKCdOdW1iZXIgbXVzdCBpZGVudGlmeSBleGFjdGx5IG9uZSBhY2NvdW50JykKICAgICAgICB1c2VyX2lkID0gcm93c1swXVswXQogICAgICAgIGlmIGNvbi5leGVjdXRlKCdERUxFVEUgRlJPTSBhZG1pbl9yb2xlcyBXSEVSRSB1c2VyX2lkPT8nLCAodXNlcl9pZCwpKS5yb3djb3VudDoKICAgICAgICAgICAgY29uLmV4ZWN1dGUoJ0lOU0VSVCBJTlRPIGFkbWluX2F1ZGl0KGFjdG9yLGFjdGlvbix0YXJnZXQsY3JlYXRlZF9hdCkgVkFMVUVTICg/LD8sPyw/KScsICgncm9vdCcsJ2FkbWluLnJldm9rZScsdXNlcl9pZCxkYXRldGltZS5ub3codGltZXpvbmUudXRjKS5pc29mb3JtYXQoKSkpCiAgICAgICAgcmV0dXJuIHVzZXJfaWQKCgpkZWYgaWRlbnRpdHkocmVxdWVzdCk6CiAgICB1c2VyX2lkID0gQ1RYWydhdXRoZW50aWNhdGVkX3VzZXJfaWQnXShyZXF1ZXN0KQogICAgd2l0aCBkYigpIGFzIGNvbjoKICAgICAgICBpZiBub3QgY29uLmV4ZWN1dGUoJ1NFTEVDVCAxIEZST00gdXNlcnMgV0hFUkUgaWQ9PycsICh1c2VyX2lkLCkpLmZldGNob25lKCk6CiAgICAgICAgICAgIHJhaXNlIEhUVFBFeGNlcHRpb24oNDAxLCAnYXV0aGVudGljYXRpb25fcmVxdWlyZWQnKQogICAgcmV0dXJuIHVzZXJfaWQKCgpkZWYgcmVxdWlyZV9hZG1pbihyZXF1ZXN0KToKICAgIHVzZXJfaWQgPSBpZGVudGl0eShyZXF1ZXN0KQogICAgd2l0aCBkYigpIGFzIGNvbjoKICAgICAgICBpZiBub3QgY29uLmV4ZWN1dGUoJ1NFTEVDVCAxIEZST00gYWRtaW5fcm9sZXMgV0hFUkUgdXNlcl9pZD0/JywgKHVzZXJfaWQsKSkuZmV0Y2hvbmUoKToKICAgICAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbig0MDMsICdhZG1pbmlzdHJhdG9yX3JlcXVpcmVkJykKICAgIHJldHVybiB1c2VyX2lkCgoKZGVmIHJlc3BvbnNlKGRhdGEpOgogICAgcmV0dXJuIEpTT05SZXNwb25zZShkYXRhLCBoZWFkZXJzPUhFQURFUlMpCgoKZGVmIHVzZXJfcmVjb3JkKGNvbiwgcm93KToKICAgIHVzZXJfaWQgPSByb3dbJ2lkJ10KICAgIG51bWJlciA9IGNvbi5leGVjdXRlKCdTRUxFQ1QgTUlOKG51bWJlcikgRlJPTSBtYW5hZ2VkX3VzZXJzIFdIRVJFIGFjY291bnRfaWQ9PyBBTkQgZGVsZXRlZF9hdCBJUyBOVUxMJywgKHVzZXJfaWQsKSkuZmV0Y2hvbmUoKVswXQogICAgYWNjZXNzID0gW2RpY3QocikgZm9yIHIgaW4gY29uLmV4ZWN1dGUoJ1NFTEVDVCB2cG5fdXNlcm5hbWUgQVMgdXNlcm5hbWUsIHNlcnZlciwgY3JlYXRlZF9hdCBBUyBjcmVhdGVkQXQgRlJPTSB2cG5fYWNjZXNzIFdIRVJFIHVzZXJfaWQ9PycsICh1c2VyX2lkLCkpXQogICAgcmV0dXJuIHsnaWQnOiB1c2VyX2lkLCAnbnVtYmVyJzogbnVtYmVyLCAnY3JlYXRlZEF0Jzogcm93WydjcmVhdGVkX2F0J10sICdhY2Nlc3MnOiBhY2Nlc3MsCiAgICAgICAgICAgICdwYXNza2V5cyc6IGNvbi5leGVjdXRlKCdTRUxFQ1QgY291bnQoKikgRlJPTSBwYXNza2V5cyBXSEVSRSB1c2VyX2lkPT8nLCAodXNlcl9pZCwpKS5mZXRjaG9uZSgpWzBdLAogICAgICAgICAgICAnd2luZG93c0RldmljZXMnOiBjb24uZXhlY3V0ZSgiU0VMRUNUIGNvdW50KCopIEZST00gd2luZG93c19kZXZpY2VzIFdIRVJFIHVzZXJfaWQ9PyBBTkQgc3RhdGUhPSdkZWxldGVkJyIsICh1c2VyX2lkLCkpLmZldGNob25lKClbMF0sCiAgICAgICAgICAgICdpc0FkbWluJzogYm9vbChjb24uZXhlY3V0ZSgnU0VMRUNUIDEgRlJPTSBhZG1pbl9yb2xlcyBXSEVSRSB1c2VyX2lkPT8nLCAodXNlcl9pZCwpKS5mZXRjaG9uZSgpKSwKICAgICAgICAgICAgJ3Byb3RlY3RlZCc6IGJvb2woY29uLmV4ZWN1dGUoJ1NFTEVDVCAxIEZST00gdnBuX2ltcG9ydHMgV0hFUkUgdXNlcl9pZD0/IEFORCBwcm90ZWN0ZWQ9MScsICh1c2VyX2lkLCkpLmZldGNob25lKCkpfQoKCmRlZiBxdWVyeV9ub2RlKG5vZGUpOgogICAgIyBOb2RlIG5hbWVzIGFyZSBmaXhlZCBieSB0aGUgY2FsbGVyOyBubyBicm93c2VyIGlucHV0IGVudGVycyBTU0ggY29tbWFuZHMuCiAgICBpZiBub2RlIG5vdCBpbiAoJ3JpZ2EnLCAnbW9zY293Jyk6CiAgICAgICAgcmFpc2UgVmFsdWVFcnJvcignaW52YWxpZCBub2RlJykKICAgIHN0YW1wID0gZGF0ZXRpbWUubm93KHRpbWV6b25lLnV0YykuaXNvZm9ybWF0KCkKICAgIGZhaWxlZCA9IHsnbm9kZSc6IG5vZGUsICdzdGF0dXMnOiAnZXJyb3InLCAnYXR0ZW1wdGVkQXQnOiBzdGFtcCwgJ2Vycm9yJzogJ25vZGVfdW5hdmFpbGFibGUnfQogICAgdHJ5OgogICAgICAgIGNvbW1hbmQgPSBbJy91c3IvYmluL3NzaCcsICctVCcsICctbycsICdCYXRjaE1vZGU9eWVzJywgJy1vJywgJ0lkZW50aXRpZXNPbmx5PXllcycsCiAgICAgICAgICAgICAgICAgICAnLW8nLCAnQ29ubmVjdFRpbWVvdXQ9MTAnLCAnLW8nLCAnU3RyaWN0SG9zdEtleUNoZWNraW5nPXllcycsCiAgICAgICAgICAgICAgICAgICAnLW8nLCAnVXNlcktub3duSG9zdHNGaWxlPScrc3RyKENUWFsnUklHQV9LTk9XTl9IT1NUUyddKSwKICAgICAgICAgICAgICAgICAgICctaScsIHN0cihDVFhbJ1JJR0FfS0VZJ10pLCBzdHIoQ1RYWydSSUdBX1VTRVInXSkrJ0AnK3N0cihDVFhbJ1JJR0FfSE9TVCddKSwKICAgICAgICAgICAgICAgICAgICdhZG1pbi1zZXNzaW9ucyAnK25vZGVdCiAgICAgICAgcmVzdWx0ID0gc3VicHJvY2Vzcy5ydW4oY29tbWFuZCwgY2FwdHVyZV9vdXRwdXQ9VHJ1ZSwgdGV4dD1UcnVlLCB0aW1lb3V0PTQwLCBjaGVjaz1GYWxzZSkKICAgICAgICBpZiByZXN1bHQucmV0dXJuY29kZSBvciBsZW4ocmVzdWx0LnN0ZG91dCkgPiA4ICogMTAyNCAqIDEwMjQ6CiAgICAgICAgICAgIHJldHVybiBmYWlsZWQKICAgICAgICB2YWx1ZSA9IGpzb24ubG9hZHMocmVzdWx0LnN0ZG91dCkKICAgICAgICBpZiBub3QgaXNpbnN0YW5jZSh2YWx1ZSwgZGljdCkgb3IgdmFsdWUuZ2V0KCdzdGF0dXMnKSAhPSAnb2snIG9yIHZhbHVlLmdldCgnbm9kZScpICE9IG5vZGUgb3IgdmFsdWUuZ2V0KCd2ZXJzaW9uJykgIT0gJzEuMC4wJzoKICAgICAgICAgICAgcmV0dXJuIGZhaWxlZAogICAgICAgIG9ic2VydmVkID0gdmFsdWUuZ2V0KCdvYnNlcnZlZEF0JykKICAgICAgICBwYXJzZWQgPSBkYXRldGltZS5mcm9taXNvZm9ybWF0KG9ic2VydmVkKQogICAgICAgIGlmIHBhcnNlZC51dGNvZmZzZXQoKSBpcyBOb25lOgogICAgICAgICAgICByZXR1cm4gZmFpbGVkCiAgICAgICAgc291cmNlID0gdmFsdWUuZ2V0KCdzZXNzaW9ucycpCiAgICAgICAgaWYgbm90IGlzaW5zdGFuY2Uoc291cmNlLCBsaXN0KSBvciBsZW4oc291cmNlKSA+IDEwMDAwOgogICAgICAgICAgICByZXR1cm4gZmFpbGVkCiAgICAgICAgc2Vzc2lvbnMgPSBbXQogICAgICAgIGlkcyA9IHNldCgpCiAgICAgICAgZm9yIHJvdyBpbiBzb3VyY2U6CiAgICAgICAgICAgIGlmIG5vdCBpc2luc3RhbmNlKHJvdywgZGljdCk6CiAgICAgICAgICAgICAgICByZXR1cm4gZmFpbGVkCiAgICAgICAgICAgIGNsZWFuID0ge30KICAgICAgICAgICAgZm9yIGtleSBpbiAoJ2lkJywgJ2VzdGFibGlzaGVkU2Vjb25kcycsICdieXRlc0luJywgJ2J5dGVzT3V0Jyk6CiAgICAgICAgICAgICAgICB2ID0gcm93LmdldChrZXkpCiAgICAgICAgICAgICAgICBpZiBrZXkgPT0gJ2VzdGFibGlzaGVkU2Vjb25kcycgYW5kIHYgaXMgTm9uZToKICAgICAgICAgICAgICAgICAgICBjbGVhbltrZXldID0gTm9uZQogICAgICAgICAgICAgICAgICAgIGNvbnRpbnVlCiAgICAgICAgICAgICAgICBpZiB0eXBlKHYpIGlzIG5vdCBpbnQgb3IgdiA8IDA6CiAgICAgICAgICAgICAgICAgICAgcmV0dXJuIGZhaWxlZAogICAgICAgICAgICAgICAgY2xlYW5ba2V5XSA9IHYKICAgICAgICAgICAgaWYgY2xlYW5bJ2lkJ10gaW4gaWRzOgogICAgICAgICAgICAgICAgcmV0dXJuIGZhaWxlZAogICAgICAgICAgICBpZHMuYWRkKGNsZWFuWydpZCddKQogICAgICAgICAgICBmb3Iga2V5IGluICgnY29ubmVjdGlvbicsICdzdGF0ZScsICdpZGVudGl0eScsICdpZGVudGl0eVNvdXJjZScsICdyZW1vdGVIb3N0Jyk6CiAgICAgICAgICAgICAgICB2ID0gcm93LmdldChrZXkpCiAgICAgICAgICAgICAgICBpZiB2IGlzIG5vdCBOb25lIGFuZCAobm90IGlzaW5zdGFuY2Uodiwgc3RyKSBvciBsZW4odikgPiAxMDI0KToKICAgICAgICAgICAgICAgICAgICByZXR1cm4gZmFpbGVkCiAgICAgICAgICAgICAgICBjbGVhbltrZXldID0gdgogICAgICAgICAgICBpZiBjbGVhblsnaWRlbnRpdHlTb3VyY2UnXSBub3QgaW4gKCdyZW1vdGUtaWQnLCAncmVtb3RlLWVhcC1pZCcpOgogICAgICAgICAgICAgICAgcmV0dXJuIGZhaWxlZAogICAgICAgICAgICB2aXBzID0gcm93LmdldCgndmlydHVhbEFkZHJlc3NlcycpCiAgICAgICAgICAgIGlmIG5vdCBpc2luc3RhbmNlKHZpcHMsIGxpc3QpIG9yIGxlbih2aXBzKSA+IDMyIG9yIGFueShub3QgaXNpbnN0YW5jZSh2LCBzdHIpIG9yIGxlbih2KSA+IDEyOCBmb3IgdiBpbiB2aXBzKToKICAgICAgICAgICAgICAgIHJldHVybiBmYWlsZWQKICAgICAgICAgICAgY2xlYW5bJ3ZpcnR1YWxBZGRyZXNzZXMnXSA9IHZpcHMKICAgICAgICAgICAgc2Vzc2lvbnMuYXBwZW5kKGNsZWFuKQogICAgICAgIHJldHVybiB7J25vZGUnOiBub2RlLCAnc3RhdHVzJzogJ29rJywgJ29ic2VydmVkQXQnOiBvYnNlcnZlZCwgJ3Nlc3Npb25zJzogc2Vzc2lvbnN9CiAgICBleGNlcHQgKEtleUVycm9yLCBWYWx1ZUVycm9yLCBUeXBlRXJyb3IsIE9TRXJyb3IsIHN1YnByb2Nlc3MuVGltZW91dEV4cGlyZWQpOgogICAgICAgIHJldHVybiBmYWlsZWQKCgpkZWYgbWFwX3Nlc3Npb24oY29uLCBzZXNzaW9uKToKICAgIHVzZXJuYW1lID0gc2Vzc2lvbi5nZXQoJ2lkZW50aXR5JykKICAgIGlmIG5vdCB1c2VybmFtZToKICAgICAgICByZXR1cm4gTm9uZQogICAgcm93cyA9IGNvbi5leGVjdXRlKCJTRUxFQ1QgYWNjb3VudF9pZCxudW1iZXIgRlJPTSBtYW5hZ2VkX3VzZXJzIFdIRVJFIHZwbl91c2VybmFtZT0/IEFORCBkZWxldGVkX2F0IElTIE5VTEwiLCAodXNlcm5hbWUsKSkuZmV0Y2hhbGwoKQogICAgcm93cyArPSBjb24uZXhlY3V0ZSgiU0VMRUNUIHcudXNlcl9pZCxtLm51bWJlciBGUk9NIHdpbmRvd3NfZGV2aWNlcyB3IEpPSU4gdXNlcnMgdSBPTiB1LmlkPXcudXNlcl9pZCBMRUZUIEpPSU4gbWFuYWdlZF91c2VycyBtIE9OIG0uYWNjb3VudF9pZD13LnVzZXJfaWQgQU5EIG0uZGVsZXRlZF9hdCBJUyBOVUxMIFdIRVJFIHcudXNlcm5hbWU9PyBBTkQgdy5zdGF0ZSE9J2RlbGV0ZWQnIiwgKHVzZXJuYW1lLCkpLmZldGNoYWxsKCkKICAgIG1hdGNoZXMgPSB7KHJvd1swXSwgcm93WzFdKSBmb3Igcm93IGluIHJvd3N9CiAgICAjIERpc3BsYXktb25seSByZWdpc3RyeSBtYXRjaDsgbmV2ZXIgYXV0aG9yaXphdGlvbiBmb3IgYSBtdXRhdGlvbi4KICAgIGlmIGxlbihtYXRjaGVzKSAhPSAxOgogICAgICAgIHJldHVybiBOb25lCiAgICBhY2NvdW50X2lkLCBudW1iZXIgPSBtYXRjaGVzLnBvcCgpCiAgICByZXR1cm4geydhY2NvdW50SWQnOiBhY2NvdW50X2lkLCAnbnVtYmVyJzogbnVtYmVyfQoKCmRlZiBpbnN0YWxsKGFwcCwgY29udGV4dCk6CiAgICBnbG9iYWwgQ1RYLCBIVFRQRXhjZXB0aW9uLCBKU09OUmVzcG9uc2UKICAgIGZyb20gZmFzdGFwaSBpbXBvcnQgSFRUUEV4Y2VwdGlvbiwgUmVxdWVzdAogICAgZnJvbSBmYXN0YXBpLnJlc3BvbnNlcyBpbXBvcnQgSlNPTlJlc3BvbnNlCiAgICBDVFggPSBjb250ZXh0CiAgICBpbml0aWFsaXplKENUWFsnREInXSkKCiAgICBAYXBwLmdldCgnL2FkbWluL2NhcGFiaWxpdGllcycpCiAgICBkZWYgY2FwYWJpbGl0aWVzKCk6CiAgICAgICAgcmV0dXJuIHJlc3BvbnNlKHsndmVyc2lvbic6IFZFUlNJT04sICdpbnZlbnRvcnknOiBUcnVlLCAnc2Vzc2lvbnMnOiBUcnVlLCAnZGlzY29ubmVjdCc6IEZhbHNlLCAnc3VzcGVuZCc6IEZhbHNlfSkKCiAgICBAYXBwLmdldCgnL2FkbWluL21lJykKICAgIGRlZiBtZShyZXF1ZXN0OiBSZXF1ZXN0KToKICAgICAgICB1c2VyX2lkID0gaWRlbnRpdHkocmVxdWVzdCkKICAgICAgICB3aXRoIGRiKCkgYXMgY29uOgogICAgICAgICAgICBudW1iZXIgPSBjb24uZXhlY3V0ZSgnU0VMRUNUIE1JTihudW1iZXIpIEZST00gbWFuYWdlZF91c2VycyBXSEVSRSBhY2NvdW50X2lkPT8gQU5EIGRlbGV0ZWRfYXQgSVMgTlVMTCcsICh1c2VyX2lkLCkpLmZldGNob25lKClbMF0KICAgICAgICAgICAgYWxsb3dlZCA9IGJvb2woY29uLmV4ZWN1dGUoJ1NFTEVDVCAxIEZST00gYWRtaW5fcm9sZXMgV0hFUkUgdXNlcl9pZD0/JywgKHVzZXJfaWQsKSkuZmV0Y2hvbmUoKSkKICAgICAgICByZXR1cm4gcmVzcG9uc2Uoeydpc0FkbWluJzogYWxsb3dlZCwgJ251bWJlcic6IG51bWJlciwgJ2ZlYXR1cmVzJzogeydzZXNzaW9ucyc6IFRydWV9fSkKCiAgICBAYXBwLmdldCgnL2FkbWluL3Nlc3Npb25zJykKICAgIGRlZiBzZXNzaW9ucyhyZXF1ZXN0OiBSZXF1ZXN0KToKICAgICAgICByZXF1aXJlX2FkbWluKHJlcXVlc3QpCiAgICAgICAgaWYgbm90IFNFU1NJT05fUE9MTC5hY3F1aXJlKGJsb2NraW5nPUZhbHNlKToKICAgICAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbig0MjksICdzZXNzaW9uX3BvbGxfaW5fcHJvZ3Jlc3MnKQogICAgICAgIHRyeToKICAgICAgICAgICAgd2l0aCBUaHJlYWRQb29sRXhlY3V0b3IobWF4X3dvcmtlcnM9MikgYXMgcG9vbDoKICAgICAgICAgICAgICAgIHJlc3VsdHMgPSBsaXN0KHBvb2wubWFwKHF1ZXJ5X25vZGUsICgncmlnYScsICdtb3Njb3cnKSkpCiAgICAgICAgICAgICMgUmVjaGVjayBhZnRlciB0aGUgcmVtb3RlIHdhaXQsIHNvIGEgcmV2b2tlZCByb2xlIGNhbm5vdCByZWNlaXZlIGEgbGF0ZSByZXNwb25zZS4KICAgICAgICAgICAgcmVxdWlyZV9hZG1pbihyZXF1ZXN0KQogICAgICAgICAgICB3aXRoIGRiKCkgYXMgY29uOgogICAgICAgICAgICAgICAgZm9yIHJlc3VsdCBpbiByZXN1bHRzOgogICAgICAgICAgICAgICAgICAgIGlmIHJlc3VsdFsnc3RhdHVzJ10gPT0gJ29rJzoKICAgICAgICAgICAgICAgICAgICAgICAgZm9yIHNlc3Npb24gaW4gcmVzdWx0WydzZXNzaW9ucyddOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgc2Vzc2lvblsnYWNjb3VudCddID0gbWFwX3Nlc3Npb24oY29uLCBzZXNzaW9uKQogICAgICAgICAgICByZXR1cm4gcmVzcG9uc2Uoeydub2Rlcyc6IHJlc3VsdHMsICdzb3VyY2UnOiAndnBuX25vZGVzJ30pCiAgICAgICAgZmluYWxseToKICAgICAgICAgICAgU0VTU0lPTl9QT0xMLnJlbGVhc2UoKQoKICAgIEBhcHAuZ2V0KCcvYWRtaW4vdXNlcnMnKQogICAgZGVmIHVzZXJzKHJlcXVlc3Q6IFJlcXVlc3QsIHE6IHN0ciA9ICcnLCBvZmZzZXQ6IGludCA9IDAsIGxpbWl0OiBpbnQgPSA1MCk6CiAgICAgICAgcmVxdWlyZV9hZG1pbihyZXF1ZXN0KQogICAgICAgIGlmIG9mZnNldCA8IDAgb3Igbm90IDEgPD0gbGltaXQgPD0gMTAwIG9yIGxlbihxKSA+IDEyODoKICAgICAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbig0MDAsICdpbnZhbGlkX3F1ZXJ5JykKICAgICAgICBxID0gcS5zdHJpcCgpCiAgICAgICAgIyBpbnN0ciBzZWFyY2hlcyBsaXRlcmFsbHk6ICUsIF8gYW5kIFNRTC1sb29raW5nIGlucHV0IGhhdmUgbm8gc3BlY2lhbCBtZWFuaW5nLgogICAgICAgIHdoZXJlID0gJycnV0hFUkUgKD89JycgT1IgaW5zdHIobG93ZXIodS5pZCksbG93ZXIoPykpPjAKICAgICAgICAgICAgT1IgRVhJU1RTKFNFTEVDVCAxIEZST00gbWFuYWdlZF91c2VycyBtIFdIRVJFIG0uYWNjb3VudF9pZD11LmlkIEFORCAoQ0FTVChtLm51bWJlciBBUyBURVhUKT0/IE9SIGluc3RyKGxvd2VyKENPQUxFU0NFKG0udnBuX3VzZXJuYW1lLCcnKSksbG93ZXIoPykpPjApKQogICAgICAgICAgICBPUiBFWElTVFMoU0VMRUNUIDEgRlJPTSB3aW5kb3dzX2RldmljZXMgdyBXSEVSRSB3LnVzZXJfaWQ9dS5pZCBBTkQgdy5zdGF0ZSE9J2RlbGV0ZWQnIEFORCBpbnN0cihsb3dlcih3Lm5hbWUpLGxvd2VyKD8pKT4wKSknJycKICAgICAgICBhcmdzID0gKHEscSxxLHEscSkKICAgICAgICB3aXRoIGRiKCkgYXMgY29uOgogICAgICAgICAgICB0b3RhbCA9IGNvbi5leGVjdXRlKCdTRUxFQ1QgY291bnQoKikgRlJPTSB1c2VycyB1ICcrd2hlcmUsYXJncykuZmV0Y2hvbmUoKVswXQogICAgICAgICAgICByb3dzID0gY29uLmV4ZWN1dGUoJ1NFTEVDVCB1LmlkLHUuY3JlYXRlZF9hdCBGUk9NIHVzZXJzIHUgJyt3aGVyZSsnIE9SREVSIEJZIHUuY3JlYXRlZF9hdCBERVNDLHUuaWQgTElNSVQgPyBPRkZTRVQgPycsIGFyZ3MrKGxpbWl0LG9mZnNldCkpLmZldGNoYWxsKCkKICAgICAgICAgICAgdmFsdWVzID0gW3VzZXJfcmVjb3JkKGNvbixyKSBmb3IgciBpbiByb3dzXQogICAgICAgIHJldHVybiByZXNwb25zZSh7J3VzZXJzJzp2YWx1ZXMsJ3RvdGFsJzp0b3RhbCwnb2Zmc2V0JzpvZmZzZXQsJ2xpbWl0JzpsaW1pdCwnb2JzZXJ2ZWRBdCc6ZGF0ZXRpbWUubm93KHRpbWV6b25lLnV0YykuaXNvZm9ybWF0KCksJ3NvdXJjZSc6J2FjY291bnRfZGF0YWJhc2UnfSkKCiAgICBAYXBwLmdldCgnL2FkbWluL3VzZXJzL3t1c2VyX2lkfScpCiAgICBkZWYgZGV0YWlscyh1c2VyX2lkOiBzdHIsIHJlcXVlc3Q6IFJlcXVlc3QpOgogICAgICAgIHJlcXVpcmVfYWRtaW4ocmVxdWVzdCkKICAgICAgICB0cnk6CiAgICAgICAgICAgIHVzZXJfaWQgPSBzdHIodXVpZC5VVUlEKHVzZXJfaWQpKQogICAgICAgIGV4Y2VwdCBWYWx1ZUVycm9yOgogICAgICAgICAgICByYWlzZSBIVFRQRXhjZXB0aW9uKDQwMCwgJ2ludmFsaWRfdXNlcl9pZCcpCiAgICAgICAgd2l0aCBkYigpIGFzIGNvbjoKICAgICAgICAgICAgcm93ID0gY29uLmV4ZWN1dGUoJ1NFTEVDVCBpZCxjcmVhdGVkX2F0IEZST00gdXNlcnMgV0hFUkUgaWQ9PycsICh1c2VyX2lkLCkpLmZldGNob25lKCkKICAgICAgICAgICAgaWYgbm90IHJvdzoKICAgICAgICAgICAgICAgIHJhaXNlIEhUVFBFeGNlcHRpb24oNDA0LCAndXNlcl9ub3RfZm91bmQnKQogICAgICAgICAgICByZXN1bHQgPSB1c2VyX3JlY29yZChjb24scm93KQogICAgICAgICAgICByZXN1bHRbJ2RldmljZXMnXSA9IFtkaWN0KHIpIGZvciByIGluIGNvbi5leGVjdXRlKCJTRUxFQ1Qgdy5pZCx3Lm5hbWUsdy51c2VybmFtZSx3LnN0YXRlLHcuY3JlYXRlZF9hdCBBUyBjcmVhdGVkQXQsQ09BTEVTQ0Uobi5zZXJ2ZXIsJ3JpZ2EnKSBBUyBzZXJ2ZXIgRlJPTSB3aW5kb3dzX2RldmljZXMgdyBMRUZUIEpPSU4gd2luZG93c19kZXZpY2Vfbm9kZXMgbiBPTiBuLmRldmljZV9pZD13LmlkIFdIRVJFIHcudXNlcl9pZD0/IEFORCB3LnN0YXRlIT0nZGVsZXRlZCcgT1JERVIgQlkgdy5jcmVhdGVkX2F0LHcuaWQiLCh1c2VyX2lkLCkpXQogICAgICAgICAgICByZXN1bHRbJ3Bhc3NrZXlOYW1lcyddID0gW3JbMF0gb3IgJycgZm9yIHIgaW4gY29uLmV4ZWN1dGUoJ1NFTEVDVCBuYW1lIEZST00gcGFzc2tleXMgV0hFUkUgdXNlcl9pZD0/IE9SREVSIEJZIGNyZWF0ZWRfYXQnLCh1c2VyX2lkLCkpXQogICAgICAgIHJldHVybiByZXNwb25zZShyZXN1bHQpCgogICAgQGFwcC5nZXQoJy9hZG1pbi9yZWdpc3RyeScpCiAgICBkZWYgcmVnaXN0cnkocmVxdWVzdDogUmVxdWVzdCwgb2Zmc2V0OiBpbnQgPSAwLCBsaW1pdDogaW50ID0gNTApOgogICAgICAgIHJlcXVpcmVfYWRtaW4ocmVxdWVzdCkKICAgICAgICBpZiBvZmZzZXQgPCAwIG9yIG5vdCAxIDw9IGxpbWl0IDw9IDEwMDoKICAgICAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbig0MDAsICdpbnZhbGlkX3F1ZXJ5JykKICAgICAgICB3aXRoIGRiKCkgYXMgY29uOgogICAgICAgICAgICB0b3RhbCA9IGNvbi5leGVjdXRlKCdTRUxFQ1QgY291bnQoKikgRlJPTSBtYW5hZ2VkX3VzZXJzIFdIRVJFIGRlbGV0ZWRfYXQgSVMgTlVMTCcpLmZldGNob25lKClbMF0KICAgICAgICAgICAgcm93cyA9IGNvbi5leGVjdXRlKCdTRUxFQ1QgbnVtYmVyLGFjY291bnRfaWQgQVMgYWNjb3VudElkLHZwbl91c2VybmFtZSBBUyB1c2VybmFtZSxjcmVhdGVkX2F0IEFTIGNyZWF0ZWRBdCxzb3VyY2UsdnBuX2FjdGl2ZSBBUyBwcm92aXNpb25lZCBGUk9NIG1hbmFnZWRfdXNlcnMgV0hFUkUgZGVsZXRlZF9hdCBJUyBOVUxMIE9SREVSIEJZIG51bWJlciBMSU1JVCA/IE9GRlNFVCA/JywgKGxpbWl0LG9mZnNldCkpLmZldGNoYWxsKCkKICAgICAgICByZXR1cm4gcmVzcG9uc2UoeydyZWNvcmRzJzpbZGljdChyKSBmb3IgciBpbiByb3dzXSwndG90YWwnOnRvdGFsLCdvZmZzZXQnOm9mZnNldCwnbGltaXQnOmxpbWl0LCdzb3VyY2UnOidhY2NvdW50X2RhdGFiYXNlJ30pCgogICAgQGFwcC5nZXQoJy9hZG1pbi9hdWRpdCcpCiAgICBkZWYgYXVkaXQocmVxdWVzdDogUmVxdWVzdCk6CiAgICAgICAgcmVxdWlyZV9hZG1pbihyZXF1ZXN0KQogICAgICAgIHdpdGggZGIoKSBhcyBjb246CiAgICAgICAgICAgIHJvd3MgPSBjb24uZXhlY3V0ZSgnU0VMRUNUIGFjdG9yLGFjdGlvbix0YXJnZXQsY3JlYXRlZF9hdCBBUyBjcmVhdGVkQXQgRlJPTSBhZG1pbl9hdWRpdCBPUkRFUiBCWSBpZCBERVNDIExJTUlUIDEwMCcpLmZldGNoYWxsKCkKICAgICAgICByZXR1cm4gcmVzcG9uc2UoeydldmVudHMnOltkaWN0KHIpIGZvciByIGluIHJvd3NdfSkK'
PAYLOAD_SHA256 = '71fcc9da881bf82e54fe01f9744c18505a20282b6fb7ea71ab174f22f9a6f337'
ROOT = Path('/opt/tolf-api')
DB = '/var/lib/tolf-api/tolf.db'
MARKER = '# TOLF admin inventory v1'


def patch(source):
    tree = ast.parse(source)
    names = {n.name for n in tree.body if isinstance(n,(ast.FunctionDef,ast.AsyncFunctionDef))}
    if 'authenticated_user_id' not in names:
        raise RuntimeError('Expected authentication function is missing; nothing changed')
    if MARKER in source:
        if 'tolf_admin.install(app, globals())' not in source:
            raise RuntimeError('Admin integration differs; nothing changed')
        return source
    addition = '\n'+MARKER+'\nimport tolf_admin\ntolf_admin.install(app, globals())\n'
    lines = source.splitlines(keepends=True)
    for node in tree.body:
        if isinstance(node,ast.If) and '__name__' in ast.unparse(node.test) and '__main__' in ast.unparse(node.test):
            index = node.lineno-1
            return ''.join(lines[:index])+addition+'\n'+''.join(lines[index:])
    return source.rstrip()+'\n'+addition


def module():
    spec = importlib.util.spec_from_file_location('tolf_admin_installer',ROOT/'tolf_admin.py')
    value = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(value)
    return value


def inventory():
    with sqlite3.connect('file:'+DB+'?mode=ro',uri=True) as con:
        rows = con.execute('SELECT m.number,m.vpn_username,u.id FROM managed_users m JOIN users u ON u.id=m.account_id WHERE m.deleted_at IS NULL ORDER BY m.number').fetchall()
        for number,username,user_id in rows:
            names = [r[0] for r in con.execute('SELECT name FROM passkeys WHERE user_id=? ORDER BY created_at',(user_id,)) if r[0]]
            # JSON escaping prevents control characters in user labels affecting the terminal.
            print(json.dumps({'number':number,'vpn':username,'passkeys':names},ensure_ascii=True))
        return rows


def atomic(path,data,info):
    fd,temp = tempfile.mkstemp(prefix='.'+path.name+'-',dir=path.parent)
    try:
        with os.fdopen(fd,'wb') as f:
            f.write(data);f.flush();os.fsync(f.fileno())
        os.chown(temp,info.st_uid,info.st_gid);os.chmod(temp,info.st_mode & 0o777)
        os.replace(temp,path)
    finally:
        Path(temp).unlink(missing_ok=True)


def install():
    path=ROOT/'main.py';target=ROOT/'tolf_admin.py'
    source=path.read_text();original=path.read_bytes();updated=patch(source)
    data=base64.b64decode(PAYLOAD)
    if hashlib.sha256(data).hexdigest()!=PAYLOAD_SHA256:
        raise RuntimeError('Admin payload checksum mismatch')
    compile(data,str(target),'exec');compile(updated,str(path),'exec')
    with sqlite3.connect('file:'+DB+'?mode=ro',uri=True) as con:
        required={'users':{'id','created_at'},'managed_users':{'number','account_id','vpn_username','created_at','source','vpn_active','deleted_at'},'vpn_access':{'user_id','vpn_username','created_at','server'},'passkeys':{'user_id','name','created_at'},'vpn_imports':{'user_id','protected'},'windows_devices':{'id','user_id','name','username','state','created_at'},'windows_device_nodes':{'device_id','server'}}
        for table,columns in required.items():
            actual={r[1] for r in con.execute('PRAGMA table_info('+table+')')}
            if not columns.issubset(actual):raise RuntimeError('Unsupported database schema: '+table)
    backup=Path('/root/tolf-admin-backup-'+time.strftime('%Y%m%d-%H%M%S')+'-'+str(os.getpid()));backup.mkdir(mode=0o700)
    shutil.copy2(path,backup/'main.py')
    if target.exists():shutil.copy2(target,backup/'tolf_admin.py')
    info=path.stat()
    print('Backup:',backup,flush=True)
    if path.read_bytes()!=original:raise RuntimeError('API source changed during preparation; nothing changed')
    try:
        atomic(target,data,info);atomic(path,updated.encode(),info)
        subprocess.run(['systemctl','restart','tolf-api.service'],check=True)
        for _ in range(12):
            try:
                with urllib.request.urlopen('https://api.tolf.is/admin/capabilities',timeout=5) as r:status=json.load(r)
                if status.get('version')=='1.1.0' and status.get('sessions') is True and status.get('inventory') is True:
                    print('OK: TOLF admin 1.1 API with live session inventory enabled. VPN sessions and credentials were not changed.',flush=True)
                    return
            except Exception:pass
            time.sleep(1)
        raise RuntimeError('Admin API did not pass its availability check')
    except Exception:
        atomic(path,(backup/'main.py').read_bytes(),info)
        if (backup/'tolf_admin.py').exists():atomic(target,(backup/'tolf_admin.py').read_bytes(),info)
        else:target.unlink(missing_ok=True)
        subprocess.run(['systemctl','restart','tolf-api.service'],check=False)
        print('Previous API files restored; backup:',backup)
        raise


def main():
    parser=argparse.ArgumentParser()
    group=parser.add_mutually_exclusive_group()
    group.add_argument('--grant-number',type=int)
    group.add_argument('--revoke-number',type=int)
    group.add_argument('--list-accounts',action='store_true')
    args=parser.parse_args()
    if os.geteuid()!=0 or not (ROOT/'main.py').is_file():raise SystemExit('Run as root on London EDISUK')
    import sys
    with open('/run/lock/tolf-admin-install.lock','w') as lock:
        fcntl.flock(lock,fcntl.LOCK_EX)
        if args.list_accounts:inventory();return
        if args.grant_number is not None:
            value=module().root_grant(DB,args.grant_number);print('Administrator granted to account:',args.grant_number,value);return
        if args.revoke_number is not None:
            value=module().root_revoke(DB,args.revoke_number);print('Administrator revoked:',args.revoke_number,value);return
        install()
        with sqlite3.connect(DB) as con:
            has_admin=con.execute('SELECT 1 FROM admin_roles a JOIN users u ON u.id=a.user_id LIMIT 1').fetchone()
        if not has_admin and sys.stdin.isatty():
            print('\nSelect YOUR account using its number and Passkey names:')
            inventory()
            chosen=input('Administrator account number (Enter to skip): ').strip()
            if chosen:
                if not chosen.isdecimal():raise SystemExit('Not a number. API installed; no administrator assigned.')
                module().root_grant(DB,int(chosen));print('Administrator granted to account:',chosen)
        print('Open https://vpn.tolf.is/admin/ after signing in with your Passkey.')
        if not has_admin:print('You can also assign access later: python3 '+str(Path(__file__).resolve())+' --grant-number NUMBER')

if __name__=='__main__':main()
