'use strict';
(() => {
const copy = {
 en:{title:'Administration',subtitle:'TOLF Network Suite',back:'Back to My VPN',signIn:'Sign in with Passkey',users:'Accounts',registry:'VPN registry',audit:'Activity log',refresh:'Refresh',inventoryNote:'This page shows records from the account database. Live VPN sessions and connection controls are not connected yet.',searchLabel:'Account number, VPN username or Windows device',search:'Search',previous:'Previous',next:'Next',close:'Close',loading:'Loading…',unavailable:'Administration is not available yet.',denied:'Administrator access has not been granted to this account.',accountNumber:'Your account number',auth:'Sign in on the main page, then return here.',error:'Could not load data. Try refreshing.',empty:'No records found.',account:'Account',created:'Created',vpn:'VPN access record',devices:'Windows devices',keys:'Passkeys',open:'Details',administrator:'Administrator',protected:'Protected user',none:'None',node:'Node',source:'Source',linked:'Account link',unlinked:'Not linked',provisioned:'VPN access record',yes:'Present',no:'Absent',when:'Time',actor:'Actor',action:'Action',target:'Account ID',grant:'Administrator granted',revoke:'Administrator revoked',root:'Server console',total:'Total',of:'of',accountId:'Account ID',deviceState:'Device record',active:'Configured',provisioning:'Preparing',deleting:'Deletion pending',deleted:'Deleted',riga:'Riga',moscow:'Moscow',unknown:'Unknown',names:'Passkey names'},
 ru:{title:'Администрирование',subtitle:'TOLF Network Suite',back:'Вернуться в «Мой VPN»',signIn:'Войти с Passkey',users:'Аккаунты',registry:'Реестр VPN',audit:'Журнал действий',refresh:'Обновить',inventoryNote:'Здесь показаны записи базы аккаунтов. Данные о текущих VPN-сеансах и управление соединениями ещё не подключены.',searchLabel:'Номер аккаунта, имя пользователя VPN или устройство Windows',search:'Найти',previous:'Назад',next:'Далее',close:'Закрыть',loading:'Загрузка…',unavailable:'Администрирование пока недоступно.',denied:'Этому аккаунту ещё не предоставлены права администратора.',accountNumber:'Номер вашего аккаунта',auth:'Войдите на основной странице, затем вернитесь сюда.',error:'Не удалось загрузить данные. Попробуйте обновить.',empty:'Записей не найдено.',account:'Аккаунт',created:'Создан',vpn:'Запись доступа VPN',devices:'Устройства Windows',keys:'Passkeys',open:'Подробнее',administrator:'Администратор',protected:'Защищённый пользователь',none:'Нет',node:'Узел',source:'Источник',linked:'Связь с аккаунтом',unlinked:'Не привязан',provisioned:'Запись доступа VPN',yes:'Есть',no:'Нет',when:'Время',actor:'Кто выполнил',action:'Действие',target:'ID аккаунта',grant:'Назначен администратор',revoke:'Сняты права администратора',root:'Консоль сервера',total:'Всего',of:'из',accountId:'ID аккаунта',deviceState:'Запись устройства',active:'Настроено',provisioning:'Подготовка',deleting:'Удаление ожидает завершения',deleted:'Удалено',riga:'Рига',moscow:'Москва',unknown:'Неизвестно',names:'Названия Passkey'},
 lv:{title:'Administrēšana',subtitle:'TOLF Network Suite',back:'Atgriezties pie mana VPN',signIn:'Pierakstīties ar Passkey',users:'Konti',registry:'VPN reģistrs',audit:'Darbību žurnāls',refresh:'Atjaunināt',inventoryNote:'Šeit redzami kontu datubāzes ieraksti. Pašreizējās VPN sesijas un savienojumu vadība vēl nav pievienota.',searchLabel:'Konta numurs, VPN lietotājvārds vai Windows ierīce',search:'Meklēt',previous:'Atpakaļ',next:'Tālāk',close:'Aizvērt',loading:'Ielāde…',unavailable:'Administrēšana vēl nav pieejama.',denied:'Šim kontam vēl nav piešķirtas administratora tiesības.',accountNumber:'Jūsu konta numurs',auth:'Pierakstieties galvenajā lapā un atgriezieties šeit.',error:'Neizdevās ielādēt datus. Mēģiniet atjaunināt.',empty:'Ieraksti nav atrasti.',account:'Konts',created:'Izveidots',vpn:'VPN piekļuves ieraksts',devices:'Windows ierīces',keys:'Passkeys',open:'Informācija',administrator:'Administrators',protected:'Aizsargāts lietotājs',none:'Nav',node:'Mezgls',source:'Avots',linked:'Saite ar kontu',unlinked:'Nav piesaistīts',provisioned:'VPN piekļuves ieraksts',yes:'Ir',no:'Nav',when:'Laiks',actor:'Izpildītājs',action:'Darbība',target:'Konta ID',grant:'Piešķirtas administratora tiesības',revoke:'Atceltas administratora tiesības',root:'Servera konsole',total:'Kopā',of:'no',accountId:'Konta ID',deviceState:'Ierīces ieraksts',active:'Iestatīta',provisioning:'Sagatavošana',deleting:'Dzēšana nav pabeigta',deleted:'Dzēsta',riga:'Rīga',moscow:'Maskava',unknown:'Nezināms',names:'Passkey nosaukumi'}
};
const $ = id => document.getElementById(id);
let lang;
try { lang=localStorage.getItem('tolfLanguage'); } catch {}
if(!copy[lang])lang=navigator.language.toLowerCase().startsWith('ru')?'ru':navigator.language.toLowerCase().startsWith('lv')?'lv':'en';
let tab='users',offset=0,total=0,epoch=0,detailEpoch=0,allowed=false,hiddenSince=0;
const t=key=>copy[lang][key]||copy.en[key]||key;
const node=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=String(text);if(cls)el.className=cls;return el;};
const date=value=>{const d=new Date(value);return Number.isNaN(d.valueOf())?'—':d.toLocaleString(lang==='ru'?'ru-RU':lang==='lv'?'lv-LV':'en-GB');};
async function api(path) {
 const r=await fetch('https://api.tolf.is/admin/'+path,{credentials:'include',cache:'no-store',headers:{Accept:'application/json'}});
 if(!r.ok){const e=new Error('request');e.status=r.status;throw e;}return r.json();
}
function clearData(){epoch++;detailEpoch++;$('results').replaceChildren();$('detailContent').replaceChildren();$('detail').hidden=true;$('status').textContent='';}
function gate(message){allowed=false;clearData();$('workspace').hidden=true;$('gate').hidden=false;$('gateMessage').textContent=message;}
function fail(e){if(e.status===401)gate(t('auth'));else if(e.status===403)gate(t('denied'));else $('status').textContent=t('error');}
function language(){document.documentElement.lang=lang;document.title='TOLF — '+t('title');document.querySelectorAll('[data-text]').forEach(el=>el.textContent=t(el.dataset.text));document.querySelectorAll('[data-lang]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.lang===lang)));}
function table(headers){const wrapper=node('div',undefined,'admin-table-wrap'),table=node('table',undefined,'admin-table'),head=node('thead'),row=node('tr');headers.forEach(k=>row.append(node('th',t(k))));head.append(row);const body=node('tbody');table.append(head,body);wrapper.append(table);$('results').append(wrapper);return body;}
function showUsers(data){const body=table(['account','vpn','devices','keys','created','open']);for(const u of data.users){const row=node('tr'),account=node('td',u.number==null?u.id:'#'+u.number);if(u.isAdmin)account.append(node('small',t('administrator')));if(u.protected)account.append(node('small',t('protected')));const access=node('td');if(!u.access.length)access.textContent=t('none');for(const a of u.access){access.append(node('div',a.username),node('small',t(a.server)));}const action=node('td'),button=node('button',t('open'),'secondary');button.type='button';button.addEventListener('click',()=>detail(u.id));action.append(button);row.append(account,access,node('td',u.windowsDevices),node('td',u.passkeys),node('td',date(u.createdAt)),action);body.append(row);}}
function showRegistry(data){const body=table(['account','vpn','linked','provisioned','source']);for(const u of data.records){const row=node('tr');row.append(node('td','#'+u.number),node('td',u.username||'—'),node('td',u.accountId||t('unlinked'),'admin-id'),node('td',u.provisioned?t('yes'):t('no')),node('td',u.source||'—'));body.append(row);}}
function showAudit(data){const body=table(['when','actor','action','target']);for(const e of data.events){const row=node('tr');row.append(node('td',date(e.createdAt)),node('td',e.actor==='root'?t('root'):e.actor),node('td',e.action==='admin.grant'?t('grant'):e.action==='admin.revoke'?t('revoke'):e.action),node('td',e.target,'admin-id'));body.append(row);}}
async function load(){if(!allowed)return;const own=++epoch;detailEpoch++;$('detail').hidden=true;$('detailContent').replaceChildren();$('results').replaceChildren();$('status').textContent=t('loading');$('pagination').hidden=true;$('searchForm').hidden=tab!=='users';document.querySelectorAll('[data-tab]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.tab===tab)));
 try{const query=new URLSearchParams({offset:String(offset),limit:'50'});if(tab==='users')query.set('q',$('search').value.trim());const data=await api(tab+(tab==='audit'?'':'?'+query));if(own!==epoch||!allowed)return;$('status').textContent='';total=tab==='audit'?data.events.length:data.total;if(!total){$('results').append(node('p',t('empty')));return;}if(tab==='users')showUsers(data);else if(tab==='registry')showRegistry(data);else showAudit(data);$('pageLabel').textContent=tab==='audit'?t('total')+': '+total:(offset+1)+'–'+Math.min(offset+50,total)+' '+t('of')+' '+total;$('pagination').hidden=false;$('previous').hidden=tab==='audit';$('next').hidden=tab==='audit';$('previous').disabled=offset===0;$('next').disabled=offset+50>=total;
 }catch(e){if(own===epoch)fail(e);}}
async function detail(id){const own=++detailEpoch;$('detail').hidden=true;$('detailContent').replaceChildren();try{const u=await api('users/'+encodeURIComponent(id));if(own!==detailEpoch||!allowed)return;$('detailTitle').textContent=t('account')+' '+(u.number==null?u.id:'#'+u.number);const content=$('detailContent');content.append(node('p',t('accountId')+': '+u.id,'admin-id'),node('p',t('names')+': '+(u.passkeyNames.filter(Boolean).join(', ')||t('none'))),node('h3',t('devices')));if(!u.devices.length)content.append(node('p',t('none')));for(const d of u.devices){const box=node('div',undefined,'admin-device');box.append(node('strong',d.name),node('p',t(d.server)+' · '+(d.username||'—')),node('p',t('deviceState')+': '+t(d.state),'admin-muted'));content.append(box);}$('detail').hidden=false;$('detail').scrollIntoView({block:'nearest'});}catch(e){if(own===detailEpoch)fail(e);}}
async function start(){const own=++epoch;try{const me=await api('me');if(own!==epoch)return;if(!me.isAdmin){gate(t('denied')+(me.number==null?'':' '+t('accountNumber')+': '+me.number+'.'));return;}allowed=true;$('gate').hidden=true;$('workspace').hidden=false;await load();}catch(e){if(own!==epoch)return;gate(e.status===401?t('auth'):e.status===404||e.status===503?t('unavailable'):t('error'));}}
document.querySelectorAll('[data-lang]').forEach(el=>el.addEventListener('click',()=>{lang=el.dataset.lang;try{localStorage.setItem('tolfLanguage',lang);}catch{}language();clearData();start();}));
document.querySelectorAll('[data-tab]').forEach(el=>el.addEventListener('click',()=>{tab=el.dataset.tab;offset=0;load();}));
$('searchForm').addEventListener('submit',e=>{e.preventDefault();offset=0;load();});$('refresh').addEventListener('click',()=>{clearData();start();});$('previous').addEventListener('click',()=>{offset=Math.max(0,offset-50);load();});$('next').addEventListener('click',()=>{offset+=50;load();});$('closeDetail').addEventListener('click',()=>{detailEpoch++;$('detail').hidden=true;$('detailContent').replaceChildren();});
// Revalidate the session after returning from another tab, including sign-out elsewhere.
document.addEventListener('visibilitychange',()=>{if(document.hidden){hiddenSince=Date.now();clearData();}else if(hiddenSince){hiddenSince=0;start();}});
window.addEventListener('pageshow',e=>{if(e.persisted){clearData();start();}});
language();$('gateMessage').textContent=t('loading');start();
})();
