"""Tests for the single-step iOS Cisco profile generated by the UK authority."""

import plistlib
import sys
import tempfile
from pathlib import Path
import unittest
import uuid

from cryptography.hazmat.primitives.serialization import pkcs12

SOURCE = Path(__file__).resolve().parents[2] / "setup" / "anyconnect"
sys.path.insert(0, str(SOURCE))
import tolf_oc_certificates
import tolf_oc_mobileconfig


class IosMobileConfig(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        directory = Path(self.temp.name) / "ca"
        tolf_oc_certificates.initialize(directory)
        self.ca = tolf_oc_certificates.Authority(directory)
        self.device_id = str(uuid.uuid4())
        self.device = self.ca.issue(self.device_id)
        self.device.update(id=self.device_id, label="iPhone")

    def tearDown(self):
        self.temp.cleanup()

    def profile(self, ingress, production=True):
        data = tolf_oc_mobileconfig.make_combined_profile(
            self.device, self.ca, ingress,
            "Москва" if ingress == "oc.tolf.is:4443" else "Рига",
            production=production,
        )
        return plistlib.loads(data)

    def test_full_profile_contains_existing_certificate_and_on_demand(self):
        profile = self.profile("oc.tolf.is:4443")
        cert, vpn = profile["PayloadContent"]
        self.assertEqual(cert["PayloadType"], "com.apple.security.pkcs12")
        key, identity, _ = pkcs12.load_key_and_certificates(
            cert["PayloadContent"], cert["Password"].encode()
        )
        self.assertIsNotNone(key)
        self.assertEqual(identity.serial_number, int(self.device["serial"], 16))
        self.assertEqual(vpn["VPNSubType"], "com.cisco.anyconnect")
        self.assertEqual(vpn["VPN"]["PayloadCertificateUUID"], cert["PayloadUUID"])
        self.assertEqual(vpn["VPN"]["OnDemandEnabled"], 1)
        self.assertEqual(vpn["VPN"]["OnDemandRules"], [{"Action": "Connect"}])
        self.assertEqual(vpn["VPN"]["RemoteAddress"], "oc.tolf.is:4443")
        self.assertEqual(profile["PayloadRemovalDisallowed"], False)

    def test_profile_reinstall_is_stable_but_entries_are_independent(self):
        profiles = []
        for host, city in (("oc.tolf.is:4443", "Москва"), ("oc-riga.tolf.is:443", "Рига")):
            def build():
                return plistlib.loads(tolf_oc_mobileconfig.make_combined_profile(
                    self.device, self.ca, host, city, production=True, include_buttons=True))
            first, second = build(), build()
            def identities(profile, field):
                return {p[field] for p in [profile, *profile["PayloadContent"]]}
            for field in ("PayloadUUID", "PayloadIdentifier"):
                self.assertEqual(identities(first, field), identities(second, field))
                self.assertEqual(len(identities(first, field)), 4)
            cert, vpn = first["PayloadContent"][:2]
            self.assertEqual(vpn["VPN"]["PayloadCertificateUUID"], cert["PayloadUUID"])
            self.assertEqual(vpn["VPN"]["RemoteAddress"], host)
            self.assertEqual(first["PayloadDisplayName"], "TOLF " + city + " iPhone")
            profiles.append(first)
        for field in ("PayloadUUID", "PayloadIdentifier"):
            self.assertTrue(identities(profiles[0], field).isdisjoint(identities(profiles[1], field)))
        legacy = str(uuid.uuid5(uuid.NAMESPACE_URL,
            "https://tolf.is/ios/anyconnect/" + self.device_id + "/profile")).upper()
        self.assertNotIn(legacy, [p["PayloadUUID"] for p in profiles])

    def test_single_icon_targets_its_own_shortcut(self):
        from urllib.parse import urlparse, parse_qs
        for host, city in (("oc.tolf.is:4443", "Москва"), ("oc-riga.tolf.is:443", "Рига")):
            normal = self.profile(host)
            profile = plistlib.loads(tolf_oc_mobileconfig.make_combined_profile(
                self.device, self.ca, host, city, production=True, include_buttons=True))
            self.assertEqual(len(profile["PayloadContent"]), 3)
            self.assertEqual(normal["PayloadUUID"], profile["PayloadUUID"])
            clip = profile["PayloadContent"][2]
            self.assertEqual(clip["Label"], "TOLF " + city)
            self.assertEqual(parse_qs(urlparse(clip["URL"]).query), {"name": ["TOLF " + city + " iPhone"]})
            self.assertEqual(clip["PayloadType"], "com.apple.webClip.managed")
            self.assertTrue(clip["Icon"].startswith(b"\x89PNG"))
            self.assertTrue(clip["IsRemovable"])

    def test_webclip_identity_is_stable_and_device_scoped(self):
        from tolf_oc_webclips import webclip_payloads
        one = webclip_payloads(self.device_id)
        self.assertEqual(one, webclip_payloads(self.device_id))
        other = webclip_payloads(str(uuid.uuid4()))
        self.assertTrue(set(p["PayloadUUID"] for p in one).isdisjoint(p["PayloadUUID"] for p in other))

    def test_pilot_profile_does_not_trigger_on_demand(self):
        pilot = self.profile("oc.tolf.is:4443", production=False)
        self.assertEqual(pilot["PayloadContent"][1]["VPN"]["OnDemandEnabled"], 0)
        self.assertNotIn("OnDemandRules", pilot["PayloadContent"][1]["VPN"])


if __name__ == "__main__":
    unittest.main()
