"""Tests for the single-step iOS Cisco profile generated by the UK authority."""

import plistlib
import sys
import tempfile
from pathlib import Path
import unittest
import uuid

from cryptography.hazmat.primitives.serialization import pkcs12

SOURCE = Path(__file__).resolve().parents[2] / "setup" / "anyconnect"
sys.path.insert(0, str(SOURCE))
import tolf_oc_certificates
import tolf_oc_mobileconfig


class IosMobileConfig(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        directory = Path(self.temp.name) / "ca"
        tolf_oc_certificates.initialize(directory)
        self.ca = tolf_oc_certificates.Authority(directory)
        self.device_id = str(uuid.uuid4())
        self.device = self.ca.issue(self.device_id)
        self.device.update(id=self.device_id, label="iPhone")

    def tearDown(self):
        self.temp.cleanup()

    def profile(self, ingress, production=True):
        data = tolf_oc_mobileconfig.make_combined_profile(
            self.device, self.ca, ingress,
            "Москва" if ingress == "oc.tolf.is:4443" else "Рига",
            production=production,
        )
        return plistlib.loads(data)

    def test_full_profile_contains_existing_certificate_and_on_demand(self):
        profile = self.profile("oc.tolf.is:4443")
        cert, vpn = profile["PayloadContent"]
        self.assertEqual(cert["PayloadType"], "com.apple.security.pkcs12")
        key, identity, _ = pkcs12.load_key_and_certificates(
            cert["PayloadContent"], cert["Password"].encode()
        )
        self.assertIsNotNone(key)
        self.assertEqual(identity.serial_number, int(self.device["serial"], 16))
        self.assertEqual(vpn["VPNSubType"], "com.cisco.anyconnect")
        self.assertEqual(vpn["VPN"]["PayloadCertificateUUID"], cert["PayloadUUID"])
        self.assertEqual(vpn["VPN"]["OnDemandEnabled"], 1)
        self.assertEqual(vpn["VPN"]["OnDemandRules"], [{"Action": "Connect"}])
        self.assertEqual(vpn["VPN"]["RemoteAddress"], "oc.tolf.is:4443")
        self.assertEqual(profile["PayloadRemovalDisallowed"], False)

    def test_profile_reinstall_updates_same_identity_and_entry(self):
        moscow = self.profile("oc.tolf.is:4443")
        riga = self.profile("oc-riga.tolf.is:443")
        self.assertEqual(moscow["PayloadUUID"], riga["PayloadUUID"])
        self.assertEqual(
            [p["PayloadUUID"] for p in moscow["PayloadContent"]],
            [p["PayloadUUID"] for p in riga["PayloadContent"]],
        )
        self.assertEqual(riga["PayloadContent"][1]["VPN"]["RemoteAddress"], "oc-riga.tolf.is:443")

    def test_optional_buttons_have_matching_names_and_different_icons(self):
        normal = self.profile("oc.tolf.is:4443")
        with_buttons = plistlib.loads(tolf_oc_mobileconfig.make_combined_profile(
            self.device, self.ca, "oc.tolf.is:4443", "Москва", production=True, include_buttons=True))
        self.assertEqual(len(normal["PayloadContent"]), 2)
        self.assertEqual(len(with_buttons["PayloadContent"]), 4)
        self.assertEqual(normal["PayloadUUID"], with_buttons["PayloadUUID"])
        # PKCS12 encryption is randomized, so compare the actual certificate above,
        # and verify that adding buttons preserves the VPN and both payload IDs here.
        self.assertEqual(normal["PayloadContent"][1], with_buttons["PayloadContent"][1])
        self.assertEqual(normal["PayloadContent"][0]["PayloadUUID"], with_buttons["PayloadContent"][0]["PayloadUUID"])
        on, off = with_buttons["PayloadContent"][2:]
        for mode, clip in (("ON", on), ("OFF", off)):
            self.assertEqual(clip["Label"], "TOLF " + mode)
            self.assertEqual(clip["URL"], "shortcuts://run-shortcut?name=TOLF&input=text&text=" + mode.lower())
            self.assertEqual(clip["PayloadType"], "com.apple.webClip.managed")
            self.assertTrue(clip["IsRemovable"])
            self.assertFalse(clip["FullScreen"])
            self.assertTrue(clip["Icon"].startswith(b"\x89PNG\r\n\x1a\n"))
        self.assertNotEqual(on["Icon"], off["Icon"])
        self.assertEqual(len({payload["PayloadUUID"] for payload in with_buttons["PayloadContent"]}), 4)

    def test_webclip_identity_is_stable_and_device_scoped(self):
        from tolf_oc_webclips import webclip_payloads
        one = webclip_payloads(self.device_id)
        self.assertEqual(one, webclip_payloads(self.device_id))
        other = webclip_payloads(str(uuid.uuid4()))
        self.assertTrue(set(p["PayloadUUID"] for p in one).isdisjoint(p["PayloadUUID"] for p in other))

    def test_pilot_profile_does_not_trigger_on_demand(self):
        pilot = self.profile("oc.tolf.is:4443", production=False)
        self.assertEqual(pilot["PayloadContent"][1]["VPN"]["OnDemandEnabled"], 0)
        self.assertNotIn("OnDemandRules", pilot["PayloadContent"][1]["VPN"])


if __name__ == "__main__":
    unittest.main()
