#!/bin/sh /etc/rc.common
USE_PROCD=1
START=99
STOP=10

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/python3 -u /opt/tolf-user0-routing/service.py
    procd_set_param env PYTHONPATH=/opt/tolf-routing-python
    procd_set_param respawn 3600 5 0
    procd_set_param term_timeout 60
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_stopped() {
    PYTHONPATH=/opt/tolf-routing-python /usr/bin/python3 /opt/tolf-user0-routing/service.py --cleanup
}
